language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head

# jruby-head sometimes breaks stuff, but it's passing at the moment
#matrix:
#  allow_failures:
#    - rvm: jruby-head

branches:
  only:
    - master
